title: Hao Liu
description: Assistant Professor | Civil Engineering | University of Maine

url: https://haoliu-90.github.io
baseurl: ""

remote_theme: mmistakes/minimal-mistakes

plugins:
  - jekyll-remote-theme

author:
  name: Hao Liu
  bio: Assistant Professor, Civil Engineering, University of Maine

page_width: 1400px

